# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/tobiash/Projects/DearUI/Blink2D/extern/googletest/googletest/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/tobiash/Projects/DearUI/Blink2D/extern/googletest/googletest/cmake/Config.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/tobiash/Projects/DearUI/Blink2D/extern/googletest/googletest/cmake/gtest.pc.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/tobiash/Projects/DearUI/Blink2D/extern/googletest/googletest/cmake/gtest_main.pc.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/tobiash/Projects/DearUI/Blink2D/extern/googletest/googletest/cmake/internal_utils.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.27.6/share/cmake/Modules/BasicConfigVersion-AnyNewerVersion.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.27.6/share/cmake/Modules/CMakePackageConfigHelpers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.27.6/share/cmake/Modules/CheckCSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.27.6/share/cmake/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.27.6/share/cmake/Modules/CheckLibraryExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.27.6/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.27.6/share/cmake/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.27.6/share/cmake/Modules/FindPython/Support.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.27.6/share/cmake/Modules/FindPython3.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.27.6/share/cmake/Modules/FindThreads.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.27.6/share/cmake/Modules/Internal/CheckSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.27.6/share/cmake/Modules/WriteBasicConfigVersionFile.cmake))

/Users/tobiash/Projects/DearUI/Blink2D/xcodeproject/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.27.6/bin/cmake -S/Users/tobiash/Projects/DearUI/Blink2D -B/Users/tobiash/Projects/DearUI/Blink2D/xcodeproject
